name: resto2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

# Using a modern SDK constraint that supports the required pre-release packages
environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase - Using recent, stable versions
  firebase_core: ^4.1.1
  firebase_auth: ^6.1.0
  cloud_firestore: ^6.0.2
  firebase_storage: ^13.0.2
  firebase_database: ^12.0.2
  firebase_messaging: ^16.0.2
  firebase_analytics: ^12.0.2
  firebase_app_check: ^0.4.1
  cloud_functions: ^6.0.2

  # Riverpod - Using specific 3.0.0 pre-release versions
  hooks_riverpod: ^3.0.0
  flutter_hooks: ^0.21.3+1
  riverpod_annotation: ^3.0.0

  # UI & Utils
  go_router: ^16.2.4
  google_fonts: ^6.2.1
  intl: ^0.20.2
  image_picker: ^1.1.2
  uuid: ^4.4.0
  dropdown_button2: ^2.3.9
  flutter_local_notifications: ^19.4.2
  cupertino_icons: ^1.0.8

  # Models (Serialization) - Using pre-release versions compatible with Riverpod v3
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # Build tools - Using corresponding pre-release versions
  build_runner: ^2.4.11
  riverpod_generator: ^3.0.0
  freezed: ^3.2.3
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
